export default  function() {
    // definitely ripped from https://github.com/davidchang/redux-pokedex/blob/master/constants/Pokemon.js
    return [
    { id:1, name : "Bulbasaur", type : "grass", stage : 0, caught : 0, species : "Seed Pokemon"},
    { id:2, name : "Ivysaur", type : "grass", stage : 3, caught : 0, species : "Seed Pokemon"},
    { id:3, name : "Venusaur", type : "grass", stage : 5, caught : 0, species : "Seed Pokemon"},
    { id:4, name : "Charmander", type : "fire", stage : 0, caught : 0, species : "Lizard Pokemon"},
    { id:5, name : "Charmeleon", type : "fire", stage : 3, caught : 0, species : "Flame Pokemon"},
    { id:6, name : "Charizard", type : "fire", stage : 5, caught : 0, species : "Flame Pokemon"},
    { id:7, name : "Squirtle", type : "water", stage : 0, caught : 0, species : "Tiny Turtle Pokemon"},
    { id:8, name : "Wartortle", type : "water", stage : 3, caught : 0, species : "Turtle Pokemon"},
    { id:9, name : "Blastoise", type : "water", stage : 5, caught : 0, species : "Shellfish Pokemon"},
    { id:10, name : "Caterpie", type : "bug", stage : 1, caught : 0, species : "Worm Pokemon"},
    { id:11, name : "Metapod", type : "bug", stage : 2, caught : 0, species : "Cocoon Pokemon"},
    { id:12, name : "Butterfree", type : "bug", stage : 4, caught : 0, species : "Butterfly Pokemon"},
    { id:13, name : "Weedle", type : "bug", stage : 1, caught : 0, species : "Hairy Bug Pokemon"},
    { id:14, name : "Kakuna", type : "bug", stage : 2, caught : 0, species : "Cocoon Pokemon"},
    { id:15, name : "Beedrill", type : "bug", stage : 4, caught : 0, species : "Poison Bee Pokemon"},
    { id:16, name : "Pidgey", type : "flying", stage : 1, caught : 0, species : "Tiny Bird Pokemon"},
    { id:17, name : "Pidgeotto", type : "flying", stage : 3, caught : 0, species : "Bird Pokemon"},
    { id:18, name : "Pidgeot", type : "flying", stage : 5, caught : 0, species : "Bird Pokemon"},
    { id:19, name : "Rattata", type : "normal", stage : 1, caught : 0, species : "Mouse Pokemon"},
    { id:20, name : "Raticate", type : "normal", stage : 2, caught : 0, species : "Mouse Pokemon"},
    { id:21, name : "Spearow", type : "flying", stage : 1, caught : 0, species : "Tiny Bird Pokemon"},
    { id:22, name : "Fearow", type : "flying", stage : 3, caught : 0, species : "Beak Pokemon"},
    { id:23, name : "Ekans", type : "poison", stage : 1, caught : 0, species : "Snake Pokemon"},
    { id:24, name : "Arbok", type : "poison", stage : 3, caught : 0, species : "Cobra Pokemon"},
    { id:25, name : "Pikachu", type : "electric", stage : 1, caught : 0, species : "Mouse Pokemon"},
    { id:26, name : "Raichu", type : "electric", stage : 3, caught : 0, species : "Mouse Pokemon"},
    { id:27, name : "Sandshrew", type : "ground", stage : 1, caught : 0, species : "Mouse Pokemon"},
    { id:28, name : "Sandslash", type : "ground", stage : 2, caught : 0, species : "Mouse Pokemon"},
    { id:29, name : "Nidoran F", type : "poison", stage : 1, caught : 0, species : "Poison Pin Pokemon"},
    { id:30, name : "Nidorina", type : "poison", stage : 2, caught : 0, species : "Poison Pin Pokemon"},
    { id:31, name : "Nidoqueen", type : "poison", stage : 5, caught : 0, species : "Drill Pokemon"},
    { id:32, name : "Nidoran M", type : "poison", stage : 1, caught : 0, species : "Poison Pin Pokemon"},
    { id:33, name : "Nidorino", type : "poison", stage : 2, caught : 0, species : "Poison Pin Pokemon"},
    { id:34, name : "Nidoking", type : "poison", stage : 5, caught : 0, species : "Drill Pokemon"},
    { id:35, name : "Clefairy", type : "fairy", stage : 1, caught : 0, species : "Fairy Pokemon"},
    { id:36, name : "Clefable", type : "fairy", stage : 3, caught : 0, species : "Fairy Pokemon"},
    { id:37, name : "Vuplix", type : "fire", stage : 1, caught : 0, species : "Fox Pokemon"},
    { id:38, name : "Ninetales", type : "fire", stage : 3, caught : 0, species : "Fox Pokemon"},
    { id:39, name : "Jigglypuff", type : "fairy", stage : 1, caught : 0, species : "Balloon Pokemon"},
    { id:40, name : "Wigglytuff", type : "fairy", stage : 3, caught : 0, species : "Balloon Pokemon"},
    { id:41, name : "Zubat", type : "poison", stage : 1, caught : 0, species : "Bat Pokemon"},
    { id:42, name : "Golbat", type : "poison", stage : 2, caught : 0, species : "Bat Pokemon"},
    { id:43, name : "Oddish", type : "grass", stage : 1, caught : 0, species : "Weed Pokemon"},
    { id:44, name : "Gloom", type : "grass", stage : 2, caught : 0, species : "Weed Pokemon"},
    { id:45, name : "Vileplume", type : "grass", stage : 3, caught : 0, species : "Flower Pokemon"},
    { id:46, name : "Paras", type : "bug", stage : 1, caught : 0, species : "Mushroom Pokemon"},
    { id:47, name : "Parasect", type : "bug", stage : 2, caught : 0, species : "Mushroom Pokemon"},
    { id:48, name : "Venonat", type : "bug", stage : 1, caught : 0, species : "Insect Pokemon"},
    { id:49, name : "Venomoth", type : "bug", stage : 2, caught : 0, species : "Poison Moth Pokemon"},
    { id:50, name : "Diglett", type : "ground", stage : 1, caught : 0, species : "Mole Pokemon"},
    { id:51, name : "Dugtrio", type : "ground", stage : 2, caught : 0, species : "Mole Pokemon"},
    { id:52, name : "Meowth", type : "normal", stage : 1, caught : 0, species : "Scratch Cat Pokemon"},
    { id:53, name : "Persian", type : "normal", stage : 2, caught : 0, species : "Classy Cat Pokemon"},
    { id:54, name : "Psyduck", type : "water", stage : 1, caught : 0, species : "Duck Pokemon"},
    { id:55, name : "Golduck", type : "water", stage : 2, caught : 0, species : "Duck Pokemon"},
    { id:56, name : "Mankey", type : "fighting", stage : 1, caught : 0, species : "Pig Monkey Pokemon"},
    { id:57, name : "Primeape", type : "fighting", stage : 2, caught : 0, species : "Pig Monkey Pokemon"},
    { id:58, name : "Growlithe", type : "fire", stage : 1, caught : 0, species : "Puppy Pokemon"},
    { id:59, name : "Arcanine", type : "fire", stage : 2, caught : 0, species : "Legendary Pokemon"},
    { id:60, name : "Poliwag", type : "water", stage : 1, caught : 0, species : "Tadpole Pokemon"},
    { id:61, name : "Poliwhirl", type : "water", stage : 2, caught : 0, species : "Tadpole Pokemon"},
    { id:62, name : "Poliwrath", type : "water", stage : 5, caught : 0, species : "Tadpole Pokemon"},
    { id:63, name : "Abra", type : "psychic", stage : 1, caught : 0, species : "Psi Pokemon"},
    { id:64, name : "Kadabra", type : "psychic", stage : 2, caught : 0, species : "Psi Pokemon"},
    { id:65, name : "Alakazam", type : "psychic", stage : 5, caught : 0, species : "Psi Pokemon"},
    { id:66, name : "Machop", type : "fighting", stage : 1, caught : 0, species : "Superpower Pokemon"},
    { id:67, name : "Machoke", type : "fighting", stage : 2, caught : 0, species : "Superpower Pokemon"},
    { id:68, name : "Machamp", type : "fighting", stage : 5, caught : 0, species : "Superpower Pokemon"},
    { id:69, name : "Bellsprout", type : "grass", stage : 1, caught : 0, species : "Flower Pokemon"},
    { id:70, name : "Weepinbell", type : "grass", stage : 3, caught : 0, species : "Flycatcher Pokemon"},
    { id:71, name : "Victreebel", type : "grass", stage : 5, caught : 0, species : "Flycatcher Pokemon"},
    { id:72, name : "Tentacool", type : "water", stage : 1, caught : 0, species : "Jellyfish Pokemon"},
    { id:73, name : "Tentacruel", type : "water", stage : 3, caught : 0, species : "Jellyfish Pokemon"},
    { id:74, name : "Geodude", type : "rock", stage : 1, caught : 0, species : "Rock Pokemon"},
    { id:75, name : "Graveler", type : "rock", stage : 3, caught : 0, species : "Rock Pokemon"},
    { id:76, name : "Golem", type : "rock", stage : 5, caught : 0, species : "Megaton Pokemon"},
    { id:77, name : "Ponyta", type : "fire", stage : 2, caught : 0, species : "Fire Horse Pokemon"},
    { id:78, name : "Rapidash", type : "fire", stage : 3, caught : 0, species : "Fire Horse Pokemon"},
    { id:79, name : "Slowpoke", type : "water", stage : 2, caught : 0, species : "Dopey Pokemon"},
    { id:80, name : "Slowbro", type : "water", stage : 3, caught : 0, species : "Hermit Crab Pokemon"},
    { id:81, name : "Magnemite", type : "electric", stage : 2, caught : 0, species : "Magnet Pokemon"},
    { id:82, name : "Magneton", type : "electric", stage : 3, caught : 0, species : "Magnet Pokemon"},
    { id:83, name : "Farfetch'd", type : "flying", stage : 3, caught : 0, species : "Wild Duck Pokemon"},
    { id:84, name : "Doduo", type : "flying", stage : 2, caught : 0, species : "Twin Bird Pokemon"},
    { id:85, name : "Dodrio", type : "flying", stage : 4, caught : 0, species : "Triple Bird Pokemon"},
    { id:86, name : "Seel", type : "water", stage : 3, caught : 0, species : "Sea Lion Pokemon"},
    { id:87, name : "Dewgong", type : "ice", stage : 5, caught : 0, species : "Sea Lion Pokemon"},
    { id:88, name : "Grimer", type : "poison", stage : 2, caught : 0, species : "Sludge Pokemon"},
    { id:89, name : "Muk", type : "poison", stage : 4, caught : 0, species : "Sludge Pokemon"},
    { id:90, name : "Shellder", type : "water", stage : 2, caught : 0, species : "Bivalve Pokemon"},
    { id:91, name : "Cloyster", type : "ice", stage : 4, caught : 0, species : "Bivalve Pokemon"},
    { id:92, name : "Gastly", type : "ghost", stage : 2, caught : 0, species : "Gas Pokemon"},
    { id:93, name : "Haunter", type : "ghost", stage : 3, caught : 0, species : "Gas Pokemon"},
    { id:94, name : "Gengar", type : "ghost", stage : 4, caught : 0, species : "Shadow Pokemon"},
    { id:95, name : "Onix", type : "rock", stage : 3, caught : 0, species : "Rock Snake Pokemon"},
    { id:96, name : "Drozee", type : "psychic", stage : 1, caught : 0, species : "Hypnosis Pokemon"},
    { id:97, name : "Hypno", type : "psychic", stage : 3, caught : 0, species : "Hypnosis Pokemon"},
    { id:98, name : "Krabby", type : "water", stage : 3, caught : 0, species : "River Crab Pokemon"},
    { id:99, name : "Kingler", type : "water", stage : 4, caught : 0, species : "Pincer Pokemon"},
    { id:100, name : "Voltorb", type : "electric", stage : 1, caught : 0, species : "Ball Pokemon"},
    { id:101, name : "Electrode", type : "electric", stage : 3, caught : 0, species : "Ball Pokemon"},
    { id:102, name : "Exeggcute", type : "grass", stage : 3, caught : 0, species : "Egg Pokemon"},
    { id:103, name : "Exeggutor", type : "grass", stage : 5, caught : 0, species : "Coconut Pokemon"},
    { id:104, name : "Cubone", type : "ground", stage : 3, caught : 0, species : "Lonely Pokemon"},
    { id:105, name : "Marowak", type : "ground", stage : 4, caught : 0, species : "Bone Keeper Pokemon"},
    { id:106, name : "Hitmonchan", type : "fighting", stage : 5, caught : 0, species : "Kicking Pokemon"},
    { id:107, name : "Hitmonlee", type : "fighting", stage : 5, caught : 0, species : "Punching Pokemon"},
    { id:108, name : "Lickitung", type : "normal", stage : 4, caught : 0, species : "Licking Pokemon"},
    { id:109, name : "Koffing", type : "poison", stage : 2, caught : 0, species : "Poison Gas Pokemon"},
    { id:110, name : "Weezing", type : "poison", stage : 4, caught : 0, species : "Poison Gas Pokemon"},
    { id:111, name : "Rhyhorn", type : "rock", stage : 3, caught : 0, species : "Spikes Pokemon"},
    { id:112, name : "Rhydon", type : "rock", stage : 4, caught : 0, species : "Drill Pokemon"},
    { id:113, name : "Chansey", type : "normal", stage : 4, caught : 0, species : "Egg Pokemon"},
    { id:114, name : "Tangela", type : "grass", stage : 4, caught : 0, species : "Vine Pokemon"},
    { id:115, name : "Kangaskhan", type : "normal", stage : 4, caught : 0, species : "Parent Pokemon"},
    { id:116, name : "Horsea", type : "water", stage : 1, caught : 0, species : "Dragon Pokemon"},
    { id:117, name : "Seadra", type : "water", stage : 2, caught : 0, species : "Dragon Pokemon"},
    { id:118, name : "Goldeen", type : "water", stage : 3, caught : 0, species : "Goldfish Pokemon"},
    { id:119, name : "Seaking", type : "water", stage : 4, caught : 0, species : "Goldfish Pokemon"},
    { id:120, name : "Staryu", type : "water", stage : 1, caught : 0, species : "Star Shape Pokemon"},
    { id:121, name : "Starmie", type : "water", stage : 2, caught : 0, species : "Mysterious Pokemon"},
    { id:122, name : "Mr. Mime", type : "psychic", stage : 4, caught : 0, species : "Barrier Pokemon"},
    { id:123, name : "Scyther", type : "bug", stage : 4, caught : 0, species : "Mantis Pokemon"},
    { id:124, name : "Jynx", type : "psychic", stage : 4, caught : 0, species : "Human Shape Pokemon"},
    { id:125, name : "Electabuzz", type : "electric", stage : 5, caught : 0, species : "Electric Pokemon"},
    { id:126, name : "Magmar", type : "fire", stage : 5, caught : 0, species : "Spitfire Pokemon"},
    { id:127, name : "Pinsir", type : "bug", stage : 5, caught : 0, species : "Stag Beetle Pokemon"},
    { id:128, name : "Tauros", type : "normal", stage : 4, caught : 0, species : "Wild Bull Pokemon"},
    { id:129, name : "Magikarp", type : "water", stage : 1, caught : 0, species : "Fish Pokemon"},
    { id:130, name : "Gyrados", type : "water", stage : 5, caught : 0, species : "Atrocious Pokemon"},
    { id:131, name : "Lapras", type : "water", stage : 4, caught : 0, species : "Transport Pokemon"},
    { id:132, name : "Ditto", type : "normal", stage : 4, caught : 0, species : "Transform Pokemon"},
    { id:133, name : "Eevee", type : "normal", stage : 2, caught : 0, species : "Evolution Pokemon"},
    { id:134, name : "Vaporeon", type : "water", stage : 4, caught : 0, species : "Bubble Jet Pokemon"},
    { id:135, name : "Jolteon", type : "electric", stage : 4, caught : 0, species : "Lightning Pokemon"},
    { id:136, name : "Flareon", type : "fire", stage : 4, caught : 0, species : "Flame Pokemon"},
    { id:137, name : "Porygon", type : "normal", stage : 5, caught : 0, species : "Virtual Pokemon"},
    { id:138, name : "Omanyte", type : "water", stage : 4, caught : 0, species : "Spiral Pokemon"},
    { id:139, name : "Omastar", type : "water", stage : 5, caught : 0, species : "Spiral Pokemon"},
    { id:140, name : "Kabuto", type : "rock", stage : 4, caught : 0, species : "Shellfish Pokemon"},
    { id:141, name : "Kabutops", type : "rock", stage : 5, caught : 0, species : "Shellfish Pokemon"},
    { id:142, name : "Aerodactyl", type : "flying", stage : 5, caught : 0, species : "Fossil Pokemon"},
    { id:143, name : "Snorlax", type : "normal", stage : 5, caught : 0, species : "Sleeping Pokemon"},
    { id:144, name : "Articuno", type : "ice", stage : 6, caught : 0, species : "Freeze Pokemon"},
    { id:145, name : "Zapdos", type : "electric", stage : 6, caught : 0, species : "Electric Pokemon"},
    { id:146, name : "Moltres", type : "fire", stage : 6, caught : 0, species : "Flame Pokemon"},
    { id:147, name : "Dratini", type : "dragon", stage : 4, caught : 0, species : "Dragon Pokemon"},
    { id:148, name : "Dragonair", type : "dragon", stage : 5, caught : 0, species : "Dragon Pokemon"},
    { id:149, name : "Dragonite", type : "dragon", stage : 6, caught : 0, species : "Dragon Pokemon"},
    { id:150, name : "Mewtwo", type : "psychic", stage : 6, caught : 0, species : "Genetic Pokemon"},
    { id:151, name : "Mew", type : "psychic", stage : 7, caught : 0, species : "New Species Pokemon"}
    ];
}